
server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    # mariaDB -> org.mariadb.jdbc.Driver
    url: jdbc:h2:mem:test
    # In-Memory \uBAA8\uB4DC (\uC7AC\uC2DC\uC791 \uC2DC \uB370\uC774\uD130 \uC0AD\uC81C\uB428) : mem
    # Embedded \uBAA8\uB4DC (\uB85C\uCEEC\uC5D0 \uB370\uC774\uD130 \uC800\uC7A5) : ~
    # Server \uBAA8\uB4DC (\uB85C\uCEEC\uC5D0 \uB370\uC774\uD130 \uC800\uC7A5 & H2 \uC124\uCE58 \uD544\uC694)
    # mariaDB -> jdbc:mariadb://localhost:3306/DB\uBA85
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
#        format_sql: true     # \uC548 \uB418\uAE38\uB798 \uC8FC\uC11D\uD568
